pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
        disableRestartFromStage()
    }
    tools {
        nodejs "nodejs"
    }
    stages {
        stage('install') {
            when {
                anyOf{
                    expression{env.BRANCH_NAME == 'main'}
                    expression{env.BRANCH_NAME == 'development'}
                }
            }
            steps {
                sh 'npm install'
            }
        }

        stage('create-env-dev') {
            when {
                branch 'main'
            }
            environment {
                VITE_API_URL = credentials("MOT_WEB_QA_VITE_API_URL")
                BRANCH_NAME = '${env.BRANCH_NAME}'
            }
            steps {
                echo 'Creating Enviorment varibles : '+env.BRANCH_NAME
                sh '''#!/bin/bash
                touch .env
                echo VITE_API_URL=$VITE_API_URL >> .env
                '''
            }
        }

        stage('main-dev') {
            when {
                branch 'main'
            }
            environment {
                MOT_WEB_QA_IP = credentials("MOT_WEB_QA_IP")
            }
            steps {
                withCredentials([
                    sshUserPrivateKey(credentialsId: "jenkins-ssl-money", keyFileVariable: 'sshkey')
                ]) {
                    echo 'maining the software'
                    sh '''#!/bin/bash
                    echo "Creating .ssh"
                    mkdir -p /var/lib/jenkins/.ssh
                    echo "Starting Build"
                    npm run build
                    echo "Build Completed"
                    ssh-keyscan ${MOT_WEB_QA_IP} >> /var/lib/jenkins/.ssh/known_hosts
                    echo "ssh-keyscan done"
                    ssh -i $sshkey ubuntu@${MOT_WEB_QA_IP} "mkdir -p /home/ubuntu/repo/moneytree-game-web/$BRANCH_NAME"
                    echo "directiry created"
                    rsync -avz --exclude  '.git' --delete -e "ssh -i $sshkey" ./build ubuntu@${MOT_WEB_QA_IP}:/home/ubuntu/repo/moneytree-game-web/$BRANCH_NAME
                    echo "data moved"

                    '''
                }
            }
        }

        stage('create-env-prod') {
            when {
                branch 'development'
            }
            environment {
                VITE_API_URL = credentials("MOT_WEB_PROD_VITE_API_URL")
                BRANCH_NAME = '${env.BRANCH_NAME}'
            }
            steps {
                echo 'Creating Enviorment varibles : '+env.BRANCH_NAME
                sh '''#!/bin/bash
                touch .env
                echo VITE_API_URL=$VITE_API_URL >> .env
                '''
            }
        }

        stage('development') {
            when {
                branch 'development'
            }
            environment {
                MOT_WEB_PROD_IP = credentials("MOT_WEB_PROD_IP")
            }
            steps {
                withCredentials([
                    sshUserPrivateKey(credentialsId: "jenkins-ssl-money", keyFileVariable: 'sshkey')
                ]) {
                    echo 'maining the software'
                    sh '''#!/bin/bash
                    echo "Creating .ssh"
                    mkdir -p /var/lib/jenkins/.ssh
                    echo "Starting Build"
                    npm run build
                    echo "Build Completed"
                    ssh-keyscan ${MOT_WEB_PROD_IP} >> /var/lib/jenkins/.ssh/known_hosts
                    echo "ssh-keyscan done"
                    ssh -i $sshkey ubuntu@${MOT_WEB_PROD_IP} "mkdir -p /home/ubuntu/repo/moneytree-game-web/$BRANCH_NAME"
                    echo "directiry created"
                    rsync -avz --exclude  '.git' --delete -e "ssh -i $sshkey" ./build ubuntu@${MOT_WEB_PROD_IP}:/home/ubuntu/repo/moneytree-game-web/$BRANCH_NAME
                    echo "data moved"

                    '''
                }
            }
        }
    }
}